# Minimal Mistakes Theme Settings
# Reference: https://mmistakes.github.io/minimal-mistakes/

# Theme settings
minimal_mistakes_skin: "default" # Options: "air", "aqua", "contrast", etc.

# Site settings
locale: "pt-BR"
title: "Arnobio C. H."  # Nome do site
description: "Site acadêmico de Arnobio C. H."  # Descrição curta do site
url: "https://arnobio-ch.github.io"  # URL do site
baseurl: ""  # Deixe vazio para GitHub Pages
repository: "arnobio-ch/arnobio-ch.github.io"  # Nome do repositório

# Author information
author:
  name: "Arnobio C. H."
  bio: "Professor e pesquisador em econometria aplicada."
  location: "Brasil"
  email: "arnobio@example.com"
  links:
    - label: "LinkedIn"
      url: "https://linkedin.com/in/arnobio"
    - label: "GitHub"
      url: "https://github.com/arnobio-ch"

# Social sharing
social_links:
  - name: "LinkedIn"
    url: "https://linkedin.com/in/arnobio"
  - name: "Google Scholar"
    url: "https://scholar.google.com"
  - name: "GitHub"
    url: "https://github.com/arnobio-ch"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
